add files

diff --git a/freenance/qa/backend-qa-pipeline.yaml b/freenance/qa/backend-qa-pipeline.yaml
--- a/freenance/qa/backend-qa-pipeline.yaml
+++ b/freenance/qa/backend-qa-pipeline.yaml
@@ -32,17 +32,17 @@ spec:
         }
     }
    environment {
-    APP_ENV = 'finance-dev'
-    IMAGE_BASE = 'freenance/backend-dev'
+    APP_ENV = 'finance-qa'
+    IMAGE_BASE = 'freenance/backend-qa'
     IMAGE_TAG = "v$BUILD_NUMBER"
     IMAGE_NAME = "${env.IMAGE_BASE}"
     IMAGE_NAME_LATEST = "${env.IMAGE_BASE}:latest"
-    HOST = "https://freenance.twnsnd.online"
     DOCKERFILE_NAME = "Dockerfile-new"
     DOCKER_REGISTRY = 'freenance'
     KUBECONFIG = credentials('kubernetes-jenkins')
-    NAMESPACE = 'finance-dev'
+    NAMESPACE = 'finance-qa'
     K8S_DEPLOYMENT_NAME = 'finance-service'
+    APP_LABEL = 'freenance-backend-qa'
     }
     options {
         timeout(time: 10, unit: 'MINUTES')
@@ -164,20 +164,14 @@ spec:
         }
         stage ('Сhange variables') {
             steps {
-                    sh '''sed -i 's#back\\.freenance\\.online#dev.freenance.store#g' FinanceBackend/settings.py'''
-                    sh '''sed -i "s#DOMAIN = 'freenance\\.online'#DOMAIN = 'dev.freenance.store'#g" FinanceBackend/settings.py'''
-                    sh '''sed -i 's#freenance\\.online#swagger.freenance.store#g' FinanceBackend/settings.py'''
-                    sh "sed -i 's#https://swagger.freenance.store#http://swagger.freenance.store#g' FinanceBackend/settings.py"
-                    sh "sed -i 's#localhost#swagger-dev.freenance.store#g' FinanceBackend/settings.py"
+//                    sh '''sed -i "s|https://freenance.store|https://qa.freenance.store|g" FinanceBackend/settings.py'''
+                    sh '''sed -i "s#DOMAIN = 'freenance\\.store'#DOMAIN = 'qa.freenance.store'#g" FinanceBackend/settings.py'''
+                    sh '''sed -i 's#freenance\\.store#qa.freenance.store#g' FinanceBackend/settings.py'''
+                    sh "sed -i 's#localhost#swagger-qa.freenance.store#g' FinanceBackend/settings.py"
                     sh "sed -i 's/httpx==0.24.1/httpx>=0.25.0,<0.26.0/' requirements.txt"
                     sh "cat FinanceBackend/settings.py"
             }
         }  
-        stage ('list files') {
-            steps {
-                sh "ls -la"
-            }
-         }
          stage ('Add Dockerfile') {
     steps {
         script {
@@ -209,11 +203,9 @@ COPY . .
 
 CMD ["sh", "-c", "gunicorn --bind 0.0.0.0:8000 FinanceBackend.wsgi:application & celery -A FinanceBackend worker -n workerсurrancy@%h --pool=solo --loglevel=info & celery -A FinanceBackend beat --loglevel=info"]
 
-
             """
             writeFile file: 'Dockerfile-new', text: envContent
         }
-        sh "cat Dockerfile-new"
     }
 }
         stage('Create deployment.yaml') {
@@ -238,7 +230,7 @@ apiVersion: v1
 kind: PersistentVolumeClaim
 metadata:
   namespace: {{NAMESPACE}}
-  name: freenance-pvc-dev
+  name: freenance-pvc-qa
 spec:
   accessModes:
     - ReadWriteOnce
@@ -251,10 +243,10 @@ apiVersion: v1
 kind: Service
 metadata:
   namespace: {{NAMESPACE}}
-  name: freenance-backend-service-dev
+  name: freenance-backend-service-qa
 spec:
   selector:
-    app: freenance-backend-dev
+    app: freenance-backend-qa
   type: ClusterIP
   ports:
     - protocol: TCP
@@ -264,23 +256,23 @@ spec:
 apiVersion: apps/v1
 kind: Deployment
 metadata:
-  name: freenance-backend-dev
+  name: freenance-backend-qa
   namespace: {{NAMESPACE}}
 spec:
   replicas: 1
   selector:
     matchLabels:
-      app: freenance-backend-dev
+      app: freenance-backend-qa
   template:
     metadata:
       annotations:
         fluentd.active: 'true'
       labels:
-        app: freenance-backend-dev
+        app: freenance-backend-qa
     spec:
       containers:
         - name: freenance
-          image: freenance/backend-dev:{{IMAGE_TAG}}
+          image: freenance/backend-qa:{{IMAGE_TAG}}
           ports:
             - containerPort: 8000
           resources:
@@ -288,11 +280,11 @@ spec:
               memory: "100Mi"
               cpu: "50m"
             limits:
-              memory: "1000Mi"
+              memory: "400Mi"
               cpu: "300m"
           envFrom:
             - secretRef:
-                name: finance-dev-secret
+                name: finance-qa-secret
           volumeMounts:
             - name: freenance-storage
               mountPath: /app/static
@@ -303,7 +295,7 @@ spec:
       volumes:
         - name: freenance-storage
           persistentVolumeClaim:
-            claimName: freenance-pvc-dev
+            claimName: freenance-pvc-qa
 
                                         '''
                     writeFile file: 'deployment.yaml', text: serviceYaml
@@ -332,5 +324,46 @@ spec:
                 }
             }
         }
+        stage('Wait for Pod to be Running') {
+            steps {
+                withKubeConfig([credentialsId: 'kubernetes-jenkins']) {
+                    sh '''
+                       echo " Waiting for container creating..."
+                        for i in $(seq 1 20); do
+                          con_create=$(kubectl get pods -n ${NAMESPACE} -l app=${APP_LABEL} | awk 'NR > 1 && $3 == "ContainerCreating"' | wc -l)
+                          if [ "$con_create" -eq 0 ]; then
+                            echo " Container creating: $con_create. ✅✅✅done"
+                            break 
+                          fi
+                          echo " Container creating: $con_create. Waiting..."
+                          sleep 30
+                        done
+                        for i in $(seq 1 10); do
+                          not_ready=$(kubectl get pods -n ${NAMESPACE} -l app=${APP_LABEL} | awk 'NR > 1 && $3 != "Running"' | wc -l)
+                          if [ "$not_ready" -eq 0 ]; then
+                            echo " All pods are in Ready state"
+                            break
+                          fi
+                          echo " Not ready pods: $not_ready. Waiting..."
+                          sleep 5
+                        done
+                        echo " Checking for pods in failed or non-running state..."
+                        bad_pods=$(kubectl get pods -n ${NAMESPACE} -l app=${APP_LABEL} | awk 'NR > 1 && $3 != "Running"' | awk '{print $1}')
+
+                        if [ -n "$bad_pods" ]; then
+                          echo "❌❌❌ The following pods are not in a healthy state:"
+                          echo "$bad_pods"
+                          for pod in $bad_pods; do
+                            echo "📦 Logs for $pod:"
+                            kubectl logs -n ${NAMESPACE} "$pod" --previous || kubectl logs -n ${NAMESPACE} "$pod" || true
+                          done
+                          exit 1
+                        else
+                          echo "✅✅✅ All pods are running and healthy"
+                        fi
+                    '''
+                        }
+                    }
+                }
     }
 } 
